// FAQ Data for different use cases
// This file contains FAQ content that can be imported and used with the FAQ component

export interface FAQItemProps {
  id: string;
  question: string;
  answer: string;
}

// Default FAQ content (updated content)
export const defaultFAQList: FAQItemProps[] = [
  {
    id: "1",
    question: "What is Legnext Midjourney API and how does it work?",
    answer: "Legnext provides a simple and stable API for Midjourney. You can generate images and videos using Midjourney's powerful AI directly through our API — no Discord accounts or manual setup required."
  },
  {
    id: "2", 
    question: "What Midjourney features are available through the API?",
    answer: "Our API includes all core Midjourney functions: text-to-image, upscale, variations, describe, blend, inpainting, zoom, and pan. We also support advanced parameters like --sref and --cref."
  },
  {
    id: "3",
    question: "How can I use the different generation modes?",
    answer: "We support Fast Mode and Turbo Mode. You can select the mode in your API requests to balance speed, quality, and cost."
  },
  {
    id: "4",
    question: "Is the content generated by Legnext API unique and original?",
    answer: "Yes. All content is generated by Midjourney's AI models and is unique to your prompts."
  },
  {
    id: "5",
    question: "Can beginners use Legnext's Midjourney API?",
    answer: "Absolutely. Our API is beginner-friendly with clear docs, simple guides, and easy endpoints for developers at any level."
  },
  {
    id: "6",
    question: "Can I use the content generated by Legnext API for commercial purposes?",
    answer: "Commercial use depends on Midjourney's terms of service and your subscription plan. Please check Midjourney's official terms for details on AI content usage rights."
  },
  {
    id: "7",
    question: "Can I upload images or files to the API?",
    answer: "Yes. You can upload images for features like Describe, Blend, and reference-based generation"
  },
  {
    id: "8",
    question: "How do I get support if I encounter issues?",
    answer: "You can get help through our docs, Telegram community, and direct support email. Contact us at support@legnext.ai for immediate assistance with any issues."
  }
];

// Midjourney API specific FAQ content
export const midjourneyAPIFAQList: FAQItemProps[] = [
  {
    id: "1",
    question: "What do I need to start using the Midjourney API?",
    answer: "Just sign up for a Legnext account and get your API key. No Midjourney account needed — our platform handles all the integration complexity for you."
  },
  {
    id: "2",
    question: "How many API requests do I get per plan?",
    answer: "Plans vary from 100 requests/month on Free tier up to unlimited requests on Enterprise. Each request generates 4 high-quality image variations to choose from."
  },
  {
    id: "3",
    question: "What parameters can I control via the API?",
    answer: "You can control prompts, aspect ratios, stylization levels, quality settings, and generation modes. Full parameter documentation available in our API docs."
  },
  {
    id: "4",
    question: "Can I retry generations if I don't like the results?",
    answer: "Yes. You can make new API calls with modified prompts or parameters until you get the perfect result, subject to your plan limits."
  },
  {
    id: "5",
    question: "In what formats are the generated images returned?",
    answer: "All images are returned as high-resolution URLs in standard formats (PNG/JPG). You can download and use them immediately in your applications."
  },
  {
    id: "6",
    question: "Do I need AI expertise to use this API?",
    answer: "Not at all. Our API abstracts away the complexity. You just send text prompts and receive professional AI-generated images — perfect for developers of all skill levels."
  },
  {
    id: "7",
    question: "Can I use this API for commercial applications?",
    answer: "Yes. Professional plans include full commercial usage rights, making it perfect for client projects, SaaS applications, and business use cases."
  },
  {
    id: "8",
    question: "How fast does the API respond?",
    answer: "Typical response times are 30-90 seconds per generation. Fast mode (available on Pro plans) reduces this to 15-30 seconds for priority processing."
  }
];
